language: go

go:
  - 1.13.x

before_install:
  - go mod download

script:
  - go test -race -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    recipients:
      - nikolay.a.demidov@yandex.ru
    on_success: never # default: change
    on_failure: always # default: always